version: "3.4"

services:
  sonarqube:
    image: sonarqube:8.9.7-community
    ports:
      - "9000:9000"
    volumes:
    - 'SonarQube_data:/opt/SonarQube/data'
    - 'SonarQube_extensions :/opt/SonarQube/extensions'
    - 'SonarQube_logs:/opt/SonarQube/logs'
    restart: unless-stopped

  nexus:
    image: sonatype/nexus3
    ports:
      - "8081:8081"
    volumes:
    - 'nexus-data:/nexus-data'
    restart: unless-stopped
    
  mysql-container:
    container_name: mysql-container
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: projetdevops
      MYSQL_USER: root
      MYSQL_PASSWORD:
    restart: always
    volumes:
      - mysql-container:/var/lib/mysql:rw
    image: 'mysql:latest'
    
  projetdevops-backend:
    depends_on:
      - mysql-container
    container_name: projetdevops-backend
    ports:
      - '8089:8089'
    image: goro1809/projetdevops-backend
    
volumes:
  mysql-container: { }
  SonarQube_data:
  SonarQube_extensions:
  SonarQube_logs:
  nexus-data:
