version: "2.2"

services:
  mysql-container3:
    container_name: mysql-container3
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: devopsproj
      MYSQL_ROOT_PASSWORD: root
      
    restart: unless-stopped
    image: mysql
    
  backend:
    depends_on:
      - mysql-container3
    container_name: backend
    ports:
      - '8040:8040'
    image: fourat8/projetdevops-backend
    restart: unless-stopped
    
volumes:
  mysql-container3: { }
