version: "3.4"

services:
  mysqldb:
    container_name: mysqldb
    ports:
      - '3306:3306'
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=1
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    restart: always
    volumes:
      - mysqldb:/var/lib/mysql:rw
    image: 'mysql:latest'
    
    
  projetdevops-backend:
    depends_on:
      - mysqldb
    container_name: projetdevops-backend
    ports:
      - '8089:8089'
    image: goro1809/projetdevops-backend
    
volumes:
  mysqldb:
