version: "2"

services:
 spring:
    container_name: spring
    build: .
    ports:
      - "8089:8089"
    hostname: spring
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_2:3306/devopsproj?autoReconnect=true&useSSL=false

    image: "maisonhotetest"
    depends_on:
      - mysql
      
 mysql:
    image: "mysql:5.6"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tpachato
    ports:
      - 3308:3306