version: "2.2"

services:
  mysql-container3:
    container_name: mysql-container3
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: devopsproj
      MYSQL_ROOT_PASSWORD: root
      
    restart: unless-stopped
    image: mysql
    
  projetdevops-backend2:
    depends_on:
      - mysql-container3
    container_name: projetdevops-backend2
    ports:
      - '8050:8050'
    image: fourat8/projetdevops-backend
    
volumes:
  mysql-container3: { }
