version: "2"

services:
  mysql-container3:
    container_name: mysql-container3
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=1
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    restart: always
    volumes:
      - mysql-container3:/var/lib/mysql:rw
    image: 'mysql:latest'
    
  projetdevopsbackend:
    depends_on:
      - mysql-container3
    container_name: projetdevopsbackend
    ports:
      - '8089:8089'
    image: goro1809/projetdevopsbackend

volumes:
  mysql-container3: { }